server:
  port: 80
spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      hostname: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
