server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql数据库驱动包 mysql-connector-java 6.0版本以上使用 以下使用com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 设置时区、设置字符集、关闭SSL连接
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: me.wheelchen.me.wheelchen.springcloud.entity
eureka:
  client:
    # 从Eureka Server端抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置才能配合Ribbon使用负载均衡
    fetch-registry: true
    # 将自身注册进入Eureka中
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
