server:
  port: 7001

eureka:
  instance:
    # Eureka服务端实例主机名
    hostname: localhost
  client:
    # false 表示不向Eureka注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，不需要去检索registry
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/